on:
  push:
    branches:
      - dinesh

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v1
        with:
          java-version: 11.x
      - run: java -version 
      
      - uses: subosito/flutter-action@v2
        with:
          flutter-versions: 3.3.9
          architecture: x64
      - run: cd upsc && flutter pub get
      - run: cd upsc && cp keystore.jks android/app/
      - run: cd upsc && flutter build apk --no-sound-null-safety

      - uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: upsc/build/app/outputs/flutter-apk/app-release.apk
